// Melones
Class OniMachinegun : SWWMWeapon
{
	Default
	{
		Tag "$T_ONIMACHINEGUN";
		Inventory.PickupMessage "$I_ONIMACHINEGUN";
		SWWMWeapon.Tooltip "$TT_ONIMACHINEGUN";
		Weapon.SlotNumber 5;
		Weapon.SlotPriority 1.;
		Weapon.SelectionOrder 100;
		Weapon.AmmoType1 "OniMachAmmo";
		Weapon.AmmoGive1 100;
		SWWMWeapon.DropAmmoType "ClipBox";
		+SWWMWEAPON.NOFIRSTGIVE;
	}
	States
	{
	Spawn:
		XZW1 A -1;
		Stop;
	}
}
