// THE BIG GUN
Class OniSlayer : SWWMWeapon
{
	int clipcount;
	bool chambered;

	Property ClipCount : clipcount;

	Default
	{
		Tag "$T_ONISLAYER";
		Inventory.PickupMessage "$I_ONISLAYER";
		Inventory.PickupSound "misc/w_pkup_vip";
		SWWMWeapon.Tooltip "$TT_ONISLAYER";
		Inventory.Icon "graphics/HUD/Icons/W_OniSlayer.png";
		Weapon.SlotNumber 9;
		Weapon.SlotPriority 1.;
		Weapon.SelectionOrder 8000;
		Weapon.AmmoType1 "OniBoarAmmo";
		Weapon.AmmoGive1 5;
		SWWMWeapon.DropAmmoType "RocketAmmo";
		OniSlayer.ClipCount 5;
		+SWWMWEAPON.NOFIRSTGIVE;
		+WEAPON.EXPLOSIVE;
		+WEAPON.BFG;
	}
	States
	{
	Spawn:
		XZW1 A -1;
		Stop;
	}
}
